### ISSUE TITLE
Need Help with long term OTP

### ISSUE THREAD

**Issue by rutschi100** [admin-ch/CovidCertificate-Documents#32]
Hello everyone, I wanted to ask in the round if someone had a similar situation and can possibly point us to a contact point, how we should proceed.

1. in our company we had a Covid-Master, who was equipped with all authorization from the BAG/BIT. However, it is now the case that this person is no longer working for us. Yet, according to BAG/BIT, this is the only person who can request a long-term OTP. The process for replacing this position does not seem to be defined. We are referred from one phone number to the next without really getting any help.

2. currently our long term OTP has expired. Unfortunately, we did not receive any reminder email regarding this. Due to the described situation (point 1), we are going through the same vicious circle again. Thus, we currently can not request certificates!!!

What we tried so far:

- Mail sent with all contacts with whom we had something to do so far.
- Contacted by telephone the BAG & BIT, respectively on Zurich and on Berne.

We are grateful for any tip / help.

**Comment by mofobo-bit** [comment]
Hi, this problem is not related to the code published on this repository, it's an administrative issue. However, I list below the procedures and depending on the case that concerns you, you can contact the appropriate person.

1. You are a health care professional (**required**) and wish to issue COVID certificates:
- Contact the cantonal doctor and formulate your request.
- The cantonal doctor will transmit your request to the FOITT.
- The FOITT EIAM service will onboard you
- You will have access to the [covidcertificate.admin.ch](covidcertificate.admin.ch)
- go to the case 2

2. You have access to the [covidcertificate.admin.ch](covidcertificate.admin.ch) platform and wish to obtain a LTOP.
- Formulate your request to [covid-zertifikat@bag.admin.ch](covid-zertifikat@bag.admin.ch).
- They will ask for an OTP .
- They will generate the LTOP and send it back to you.

In the meantime, if you already have access to the platform and can generate OTPs, then this is sufficient as an intermediate solution.

I close this issue because it is linked to a procedure and it is out of context with the code.
